on: push
name: Run Project Tests
jobs:
  runNpmTarget:
    name: Jest Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Jest Tests
        uses: anna-money/github-actions-npm@v2
        with:
          target: 'test'
